(ns system
  (:require [clojure.core.async :as async :refer [go-loop <!]]
            [com.stuartsierra.component :as component]
            [dumpr.core :as dumpr]))

(def conn-params
  {;; :subname "//127.0.0.1:3306/sharetribe_development?zeroDateTimeBehavior=convertToNull" ; Autogenerated when not given
   :user "root"
   :password "not-root"
   :host "127.0.0.1"
   :port 3306
   :db "sharetribe_development"
   :server-id 123})

(def id-fns {:people :id})

(def tables [:communities :people :listings])

(defn sink
  "Returns an atom containing a vector. Consumes values from channel
  ch and conj's them into the atom."
  ([ch] (sink ch identity))
  ([ch pr]
   (let [a (atom [])]
     (go-loop []
       (let [val (<! ch)]
         (if-not (nil? val)
           (do
             (pr val)
             (swap! a conj val)
             (recur))
           (pr "Channel closed."))))
     a)))

(defrecord Loader [conf]
  component/Lifecycle
    (start [this]
      (if-not (some? (:result this))
        (let [result (dumpr/load-tables tables conf)
              out-rows (sink (:out result))]
          (-> this
              (assoc :result result)
              (assoc :out-rows out-rows)))))

    (stop [this]
      (if (some? (:result this))
        (dissoc this :result)
        this)))

(defn create-loader [conf]
  (map->Loader {:conf conf}))

(defrecord Stream [conf loader]
  component/Lifecycle
  (start [this]
    (if-not (some? (:stream this))
      (let [binlog-pos (or (:binlog-pos this)
                           (-> loader :result :binlog-pos))
            stream (dumpr/binlog-stream conf binlog-pos)
            out-events (sink (:out stream))]
        (dumpr/start-binlog-stream stream)
        (-> this
            (assoc :binlog-pos binlog-pos)
            (assoc :out-events out-events)
            (assoc :stream stream)))))

  (stop [this]
    (if (some? (:stream this))
      (dumpr/close-binlog-stream (:stream this))
      (dissoc this :stream))))

(defn create-stream-continue [conf binlog-pos]
  (map->Stream {:conf conf :binlog-pos binlog-pos}))

(defn create-stream-new [conf]
  (map->Stream {:conf conf}))

(defn with-initial-load []
  (let [conf (dumpr/create-conf conn-params id-fns)]
    (component/system-map
     :conf conf
     :loader (create-loader conf)
     :streamer (component/using
                (create-stream-new conf)
                {:loader :loader}))))

(defn only-stream [binlog-pos]
  (let [conf (dumpr/create-conf conn-params id-fns)]
    (component/system-map
     :conf conf
     :streamer (create-stream-continue conf binlog-pos))))
